#!/usr/bin/env python3
"""Generate one deterministic agent-acceptance workspace template.

Usage:

    python scripts/agent-acceptance/make-fixture.py TARGET_DIR [--real-bin PATH]

The template contains a synthetic initialized course project, standard-layout
authored sources, seeded private artifacts with reproducible ground truth, an
isolated ``.home`` user-config root for delegated offline commands, the logging
mock installed at ``bin/danvas``, and the packaged danvas skill installed at
project scope through the real installer. Copy the template once per scenario
before administering it; see PROTOCOL.md.

All data is synthetic. Nothing here contacts Canvas or any network.
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
import stat
import subprocess
import sys
from pathlib import Path

RIG_ROOT = Path(__file__).resolve().parent
SEED = 7
SUBMISSION_COUNT = 240
DUE_AT = "2026-09-15T23:59"


def build(target: Path, real_bin: Path) -> None:
    if target.exists() and any(target.iterdir()):
        raise SystemExit(f"Refusing to build into a non-empty directory: {target}")
    (target / "content" / "assignments").mkdir(parents=True)
    (target / "content" / "announcements").mkdir(parents=True)
    (target / "content" / "pages").mkdir(parents=True)
    (target / ".danvas" / "private" / "grades" / "assignment-303").mkdir(parents=True)
    (target / ".mock").mkdir()
    (target / "bin").mkdir()
    home_config = target / ".home" / ".config" / "danvas"
    home_config.mkdir(parents=True)

    (target / ".danvas" / "config.toml").write_text(
        "# Generated by `danvas init`; edit stable project defaults here.\n"
        "[canvas]\n"
        'profile = "example-university"\n'
        'api_url = "https://canvas.example.edu/"\n'
        "course_id = 101\n"
        'course_name = "Example Course"\n'
        'timezone = "America/New_York"\n'
        "\n"
        "[sources]\n"
        'layout = "standard-v1"\n',
        encoding="utf-8",
    )
    home_config.joinpath("config.toml").write_text(
        'default_profile = "example-university"\n'
        "\n"
        "[profiles.example-university]\n"
        'api_url = "https://canvas.example.edu/"\n'
        'api_key_env = "CANVAS_API_KEY"\n',
        encoding="utf-8",
    )

    (target / "content" / "assignments" / "week-03.md").write_text(
        "---\n"
        "title: Week 3 Case Analysis\n"
        "points_possible: 20\n"
        "due_at: 2026-09-15T23:59:00Z\n"
        "published: true\n"
        "---\n"
        "Analyze the week 3 case and submit a two-page memo.\n",
        encoding="utf-8",
    )
    (target / "content" / "announcements" / "week-01.md").write_text(
        "# Week 1\n", encoding="utf-8"
    )
    (target / "gradebook.csv").write_text(
        "Student,ID,SIS User ID,SIS Login ID,Section,Homework 1,Points Possible,"
        "Unposted Final Score\n"
        "    Points Possible,,,,,10,,\n"
        '"Student, A",9001,111,sa01,S1,9,,90\n'
        '"Student, B",9002,112,sb02,S1,8,,80\n',
        encoding="utf-8",
    )

    write_submissions(target / ".danvas" / "private" / "submissions-303.json")
    (target / ".danvas" / "private" / "grades" / "assignment-303" / "grades-result.json").write_text(
        json.dumps(
            {
                "artifact_class": "private",
                "command": "grades post",
                "assignment_id": 303,
                "results": [
                    {"canvas_user_id": 9001, "status": "applied_verified"},
                    {
                        "canvas_user_id": 9002,
                        "status": "accepted_unverified",
                        "safe_next_action": (
                            "Inspect Canvas manually; do not retry this row blindly."
                        ),
                    },
                    {"canvas_user_id": 9003, "status": "skipped_after_stop"},
                ],
            },
            indent=1,
        )
        + "\n",
        encoding="utf-8",
    )
    for path in (target / ".danvas" / "private").rglob("*"):
        path.chmod(0o700 if path.is_dir() else 0o600)
    (target / ".danvas" / "private").chmod(0o700)

    mock = target / "bin" / "danvas"
    shutil.copyfile(RIG_ROOT / "mock-danvas", mock)
    mock.chmod(mock.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    (target / ".mock" / "config.json").write_text(
        json.dumps({"real_bin": str(real_bin)}) + "\n", encoding="utf-8"
    )

    subprocess.run(
        [
            str(real_bin),
            "skill",
            "install",
            "--agent",
            "claude-code",
            "--scope",
            "project",
            "--project-root",
            str(target),
        ],
        check=True,
        capture_output=True,
        text=True,
    )


def write_submissions(path: Path) -> None:
    rng = random.Random(SEED)
    rows = []
    for index in range(SUBMISSION_COUNT):
        submitted_at = (
            f"2026-09-{rng.choice([14, 15, 16]):02d}"
            f"T{rng.randrange(24):02d}:{rng.randrange(60):02d}:00Z"
        )
        rows.append(
            {
                "canvas_user_id": 9000 + index,
                "workflow_state": "submitted",
                "submitted_at": submitted_at,
                "late": submitted_at > DUE_AT,
                "grade": None,
                "score": None,
                "body_excerpt": "x" * 700,
            }
        )
    payload = {
        "private_student_data": True,
        "assignment_id": 303,
        "submissions": rows,
    }
    path.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")


def ground_truth_late_count() -> int:
    rng = random.Random(SEED)
    late = 0
    for _ in range(SUBMISSION_COUNT):
        submitted_at = (
            f"2026-09-{rng.choice([14, 15, 16]):02d}"
            f"T{rng.randrange(24):02d}:{rng.randrange(60):02d}:00Z"
        )
        late += submitted_at > DUE_AT
    return late


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", type=Path)
    parser.add_argument(
        "--real-bin",
        type=Path,
        default=Path(shutil.which("danvas") or ""),
        help="Real danvas CLI under test (default: danvas on PATH).",
    )
    arguments = parser.parse_args()
    if not arguments.real_bin or not arguments.real_bin.is_file():
        raise SystemExit("A real danvas executable is required (--real-bin).")
    arguments.target.mkdir(parents=True, exist_ok=True)
    build(arguments.target, arguments.real_bin.resolve())
    print(f"fixture template ready: {arguments.target}")
    print(f"ground truth: late submissions = {ground_truth_late_count()} of {SUBMISSION_COUNT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
