"""Dependency-light Canvas Page source rendering and normalization."""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlparse, urlsplit, urlunsplit

import markdown as markdown_lib
import tinycss2
from bs4 import BeautifulSoup, Comment, Tag
from markdown.extensions import Extension
from markdown.treeprocessors import Treeprocessor

from danvas.authored_content import (
    BOOLEAN,
    DATE_OR_DATETIME,
    NORMALIZED_TEXT,
    ComparisonPolicy,
    comparable_value,
    require_valid_datetimes,
)
from danvas.frontmatter import normalize_canvas_value, parse_frontmatter
from danvas.utils import canvas_object_to_dict

RENDERER_VERSION = "pages-markdown-v2"
COMPATIBILITY_PROFILE = "canvas-page-v1"
BODY_NORMALIZER_VERSION = "pages-html-v4"
PAGE_METADATA_COMPARE_FIELDS = {
    "title",
    "published",
    "front_page",
    "editing_roles",
    "publish_at",
}
PAGE_METADATA_FIELD_POLICIES: dict[str, ComparisonPolicy] = {
    "title": NORMALIZED_TEXT,
    "published": BOOLEAN,
    "front_page": BOOLEAN,
    "editing_roles": NORMALIZED_TEXT,
    "publish_at": DATE_OR_DATETIME,
}

ALLOWED_TAGS = {
    "a", "abbr", "blockquote", "br", "caption", "code", "col", "colgroup", "dd", "del",
    "details", "div", "dl", "dt", "em", "figcaption", "figure", "h1", "h2", "h3", "h4",
    "h5", "h6", "hr", "img", "ins", "kbd", "li", "mark", "ol", "p", "pre", "q", "s",
    "small", "span", "strong", "sub", "summary", "sup", "table", "tbody", "td", "tfoot",
    "th", "thead", "tr", "ul",
}
GLOBAL_ATTRS = {"class", "id", "lang", "dir", "role", "title"}
TAG_ATTRS = {
    "a": {"href", "target", "rel", "aria-label"},
    "img": {"src", "alt", "width", "height", "aria-label"},
    "ol": {"start", "reversed", "type"},
    "li": {"value"},
    "table": {"summary", "width"},
    "th": {"scope", "colspan", "rowspan", "headers", "abbr", "width"},
    "td": {"colspan", "rowspan", "headers", "width"},
    "col": {"span", "width"},
    "colgroup": {"span", "width"},
}
SAFE_CSS_PROPERTIES = {
    "background-color", "border", "border-bottom", "border-color", "border-left", "border-radius",
    "border-right", "border-style", "border-top", "border-width", "color", "display", "font-family",
    "font-size", "font-style", "font-weight", "letter-spacing", "line-height", "list-style-type",
    "margin", "margin-bottom", "margin-left", "margin-right", "margin-top", "max-width", "min-width",
    "padding", "padding-bottom", "padding-left", "padding-right", "padding-top", "text-align",
    "text-decoration", "text-transform", "vertical-align", "white-space", "width", "word-break",
}
URL_ATTRS = {"href", "src"}
UNSAFE_SCHEMES = {"javascript", "vbscript", "data"}
VOLATILE_QUERY_NAMES = {
    "access_token", "expires", "key-pair-id", "policy", "signature", "token", "verifier"
}
NONSEMANTIC_CANVAS_ATTRS = {
    "data-api-endpoint", "data-api-returntype", "data-canvas-previewable", "data-id",
    "data-mce-href", "data-mce-src", "data-mce-style",
}
LOCAL_ASSET_SUFFIXES = {
    ".avif", ".csv", ".doc", ".docx", ".gif", ".jpeg", ".jpg", ".mp3", ".mp4", ".pdf",
    ".png", ".ppt", ".pptx", ".svg", ".webp", ".xls", ".xlsx", ".zip",
}


@dataclass
class PageSource:
    source: Path
    metadata: dict[str, Any]
    body: str
    html: str
    body_sha256: str
    warnings: list[str]
    unresolved_assets: list[str]
    anchors: list[str]
    local_links: list[str]
    css_report: dict[str, Any] | None
    matching_h1_removed: bool


class MarkdownTableHeaderScopeProcessor(Treeprocessor):
    """Add column scope only to table headers generated by Markdown."""

    def run(self, root: Any) -> None:
        for table in root.iter("table"):
            for section in table:
                if section.tag != "thead":
                    continue
                for row in section:
                    if row.tag != "tr":
                        continue
                    for cell in row:
                        if (
                            cell.tag == "th"
                            and "scope" not in cell.attrib
                            and "headers" not in cell.attrib
                        ):
                            cell.set("scope", "col")


class MarkdownTableSemanticsExtension(Extension):
    def extendMarkdown(self, md: Any) -> None:
        md.treeprocessors.register(
            MarkdownTableHeaderScopeProcessor(md),
            "danvas-table-header-scope",
            5,
        )


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def canonicalize_page_url(
    value: str,
    *,
    course_id: int | None = None,
    canvas_origin: str | None = None,
) -> tuple[str, bool]:
    """Return a stable Page URL and whether an unresolved secret/expiry value was found."""
    parsed = urlsplit(value)
    query = parse_qsl(parsed.query, keep_blank_values=True)
    volatile = [
        (name, item)
        for name, item in query
        if name.casefold() in VOLATILE_QUERY_NAMES
        or name.casefold().startswith(("x-amz-", "x-goog-"))
    ]
    path = parsed.path
    course_path = re.match(r"^/courses/(\d+)(/.*)?$", path)
    file_path = re.match(r"^/(?:courses/(\d+)/)?files/(\d+)(/(?:download|preview))?/?$", path)
    relative_url = not parsed.scheme and not parsed.netloc
    trusted_origin = relative_url or same_url_origin(value, canvas_origin)
    stable_canvas = bool(course_path or file_path) and trusted_origin
    if file_path and trusted_origin:
        found_course = file_path.group(1) or (str(course_id) if course_id is not None else "")
        if found_course:
            mode = file_path.group(3) or ""
            path = f"/courses/{found_course}/files/{file_path.group(2)}{mode}"
            stable_canvas = True
    elif course_path and trusted_origin:
        path = f"/courses/{course_path.group(1)}{course_path.group(2) or ''}"
    unresolved = bool(parsed.username or parsed.password or (volatile and not stable_canvas))
    kept = [item for item in query if item not in volatile]
    kept.sort(key=lambda item: (item[0].casefold(), item[0], item[1]))
    scheme = parsed.scheme
    netloc = parsed.netloc
    if stable_canvas:
        scheme = ""
        netloc = ""
    return urlunsplit((scheme, netloc, path, urlencode(kept, doseq=True), parsed.fragment)), unresolved


def same_url_origin(value: str, canvas_origin: str | None) -> bool:
    """Return whether an absolute URL belongs to the explicitly configured Canvas origin."""
    if not canvas_origin:
        return False
    value_origin = normalized_url_origin(value)
    configured_origin = normalized_url_origin(canvas_origin)
    return (
        value_origin is not None
        and configured_origin is not None
        and value_origin == configured_origin
    )


def normalized_url_origin(value: str) -> tuple[str, str, int | None] | None:
    parsed = urlsplit(value)
    if not parsed.scheme or not parsed.hostname:
        return None
    try:
        port = parsed.port
    except ValueError:
        return None
    scheme = parsed.scheme.casefold()
    if port is None:
        port = {"http": 80, "https": 443}.get(scheme)
    return scheme, parsed.hostname.casefold(), port


def canonicalize_page_html(
    html: str,
    *,
    course_id: int | None = None,
    canvas_origin: str | None = None,
) -> dict[str, Any]:
    """Canonicalize Page URLs before hashing or writing durable output."""
    soup = BeautifulSoup(f"<div data-danvas-root>{html}</div>", "html.parser")
    root = soup.find("div", attrs={"data-danvas-root": True})
    strip_canvas_readback_edge_decorators(root)
    volatile_count = 0
    for tag in soup.find_all(True):
        for name, raw_value in list(tag.attrs.items()):
            if name in NONSEMANTIC_CANVAS_ATTRS or name.startswith("data-mce-"):
                del tag.attrs[name]
                continue
            if not isinstance(raw_value, str):
                continue
            if name not in {"href", "src", "data-api-endpoint", "data-download-url"}:
                continue
            canonical, unresolved = canonicalize_page_url(
                raw_value,
                course_id=course_id,
                canvas_origin=canvas_origin,
            )
            if unresolved:
                volatile_count += 1
            tag[name] = canonical
    normalized = normalize_html_fragment(inner_html(root))
    return {
        "html": normalized,
        "body_sha256": None if volatile_count else sha256_text(normalized),
        "body_hash_status": "blocked_volatile_url" if volatile_count else "available",
        "volatile_url_count": volatile_count,
        "body_normalizer": BODY_NORMALIZER_VERSION,
    }


def strip_canvas_readback_edge_decorators(root: Tag | None) -> None:
    """Remove non-authorable account decorators Canvas adds around a Page body."""
    if root is None:
        return
    while True:
        children = [child for child in root.children if isinstance(child, Tag)]
        if not children:
            return
        first = children[0]
        if is_canvas_readback_edge_decorator(first):
            first.decompose()
            continue
        last = children[-1]
        if is_canvas_readback_edge_decorator(last):
            last.decompose()
            continue
        return


def is_canvas_readback_edge_decorator(tag: Tag) -> bool:
    if tag.name == "link":
        rel = {str(value).casefold() for value in (tag.get("rel") or [])}
        return bool(tag.get("href")) and "stylesheet" in rel
    if tag.name == "script":
        return bool(tag.get("src")) and not tag.get_text(strip=True)
    return False


def load_page_source(
    source: Path,
    *,
    apply_css: bool = True,
    course_id: int | None = None,
    canvas_origin: str | None = None,
) -> PageSource:
    if not source.is_file():
        raise SystemExit(f"Page source not found: {source}")
    metadata, body = parse_frontmatter(source.read_text(encoding="utf-8"), source, "Page")
    title = str(metadata.get("title") or "").strip()
    if not title:
        raise SystemExit(f"Page front matter requires a non-empty title: {source}")
    metadata = normalize_page_metadata(metadata, source)
    warnings: list[str] = []
    if source.suffix.lower() in {".html", ".htm"}:
        html = body.strip()
    else:
        html = markdown_lib.markdown(
            body,
            extensions=["extra", "sane_lists", "toc", MarkdownTableSemanticsExtension()],
            extension_configs={"toc": {"permalink": False}},
        ).strip()
    html, h1_removed, h1_warning = handle_matching_h1(html, title)
    if h1_warning:
        warnings.append(h1_warning)
    validate_fragment(html, source)
    css_report = None
    css_ref = metadata.get("canvas_css")
    if apply_css and css_ref:
        css_path = (source.parent / str(css_ref)).resolve()
        css_report, html = check_and_inline_css(css_path, html)
        if css_report["errors"]:
            raise SystemExit(format_css_errors(css_path, css_report))
        warnings.extend(css_report["warnings"])
        validate_fragment(html, source)
    canonical = canonicalize_page_html(
        html,
        course_id=course_id,
        canvas_origin=canvas_origin,
    )
    if canonical["body_hash_status"] != "available":
        raise SystemExit("Page source contains an unresolved volatile or signed URL.")
    html = canonical["html"]
    anchors, local_links = fragment_anchors(html)
    missing = sorted(set(local_links) - set(anchors))
    if missing:
        raise SystemExit(f"Page has same-page links without rendered targets: {', '.join(missing)}")
    unresolved = unresolved_local_assets(html, source)
    return PageSource(
        source=source,
        metadata=metadata,
        body=body,
        html=html,
        body_sha256=str(canonical["body_sha256"]),
        warnings=warnings,
        unresolved_assets=unresolved,
        anchors=anchors,
        local_links=local_links,
        css_report=css_report,
        matching_h1_removed=h1_removed,
    )


def normalize_page_metadata(metadata: dict[str, Any], source: Path) -> dict[str, Any]:
    allowed = {
        "title", "page_id", "canvas_id", "published", "front_page", "editing_roles",
        "publish_at", "notify_of_update", "canvas_css", "css_policy",
        "lint_suppress",
    }
    unknown = sorted(set(metadata) - allowed)
    if unknown:
        raise SystemExit(f"Unsupported Page front matter in {source}: {', '.join(unknown)}")
    require_valid_datetimes(
        metadata,
        {"publish_at": DATE_OR_DATETIME},
        source_type="Page",
    )
    result = {key: normalize_canvas_value(value) for key, value in metadata.items()}
    result.setdefault("published", False)
    result.setdefault("front_page", False)
    result.setdefault("notify_of_update", False)
    for field in ("published", "front_page", "notify_of_update"):
        normalized = comparable_value(result[field], BOOLEAN)
        if not isinstance(normalized, bool):
            raise SystemExit(f"Page {field} must be true or false: {source}")
        result[field] = normalized
    if result.get("css_policy", "strict") != "strict":
        raise SystemExit("Only css_policy: strict is supported.")
    return result


def handle_matching_h1(html: str, title: str) -> tuple[str, bool, str | None]:
    soup = BeautifulSoup(f"<div data-danvas-root>{html}</div>", "html.parser")
    root = soup.find("div", attrs={"data-danvas-root": True})
    first = next((node for node in root.children if isinstance(node, Tag)), None) if root else None
    if first and first.name == "h1":
        if normalize_text(first.get_text(" ")) == normalize_text(title):
            first.decompose()
            return inner_html(root), True, None
        return inner_html(root), False, "First H1 does not match the Page title and was preserved."
    return inner_html(root), False, None


def normalize_text(value: str) -> str:
    return " ".join(value.casefold().split())


def validate_fragment(html: str, source: Path | None = None) -> None:
    soup = BeautifulSoup(html, "html.parser")
    for comment in soup.find_all(string=lambda text: isinstance(text, Comment)):
        comment.extract()
    for tag in soup.find_all(True):
        if tag.name not in ALLOWED_TAGS:
            raise SystemExit(f"Unsupported or unsafe <{tag.name}> in Page source{source_label(source)}.")
        for name, value in tag.attrs.items():
            lowered = name.lower()
            if lowered.startswith("on"):
                raise SystemExit(f"Event-handler attribute {name!r} is not allowed{source_label(source)}.")
            allowed = lowered in GLOBAL_ATTRS or lowered.startswith("aria-") or lowered in TAG_ATTRS.get(tag.name, set())
            if lowered == "style":
                allowed = True
                errors = validate_inline_style(str(value))
                if errors:
                    raise SystemExit(f"Unsafe inline style{source_label(source)}: {'; '.join(errors)}")
            if not allowed:
                raise SystemExit(f"Attribute {name!r} is not allowed on <{tag.name}>{source_label(source)}.")
            if lowered in URL_ATTRS and unsafe_url(str(value), allow_fragment=True):
                raise SystemExit(f"Unsafe URL in {lowered}{source_label(source)}: {value}")


def source_label(source: Path | None) -> str:
    return f" {source}" if source else ""


def validate_inline_style(style: str) -> list[str]:
    errors: list[str] = []
    for item in tinycss2.parse_declaration_list(style, skip_whitespace=True, skip_comments=True):
        if item.type == "error":
            errors.append(item.message)
        elif item.type != "declaration":
            errors.append(f"unsupported CSS token {item.type}")
        elif item.lower_name not in SAFE_CSS_PROPERTIES:
            errors.append(f"unsupported property {item.lower_name}")
        elif item.important:
            errors.append("!important is not supported")
        elif unsafe_css_value(tinycss2.serialize(item.value).strip()):
            errors.append(f"unsafe value for {item.lower_name}")
    return errors


def unsafe_url(value: str, *, allow_fragment: bool) -> bool:
    stripped = value.strip()
    if allow_fragment and stripped.startswith("#"):
        return False
    parsed = urlparse(stripped)
    return parsed.scheme.casefold() in UNSAFE_SCHEMES


def unsafe_css_value(value: str) -> bool:
    lowered = value.casefold().replace(" ", "")
    return any(token in lowered for token in ("url(", "expression(", "javascript:", "var("))


def unresolved_local_assets(html: str, source: Path) -> list[str]:
    soup = BeautifulSoup(html, "html.parser")
    result: set[str] = set()
    for tag, attr in (("img", "src"), ("a", "href")):
        for node in soup.find_all(tag):
            value = str(node.get(attr) or "").strip()
            if not value or value.startswith(("#", "/", "mailto:", "tel:")):
                continue
            parsed = urlparse(value)
            if parsed.scheme or parsed.netloc:
                continue
            candidate = parsed.path
            if tag == "img" or Path(candidate).suffix.lower() in LOCAL_ASSET_SUFFIXES:
                result.add(candidate)
    return sorted(result)


def fragment_anchors(html: str) -> tuple[list[str], list[str]]:
    soup = BeautifulSoup(html, "html.parser")
    anchors = sorted({str(node["id"]) for node in soup.find_all(id=True)})
    links = sorted({str(node["href"])[1:] for node in soup.find_all("a", href=True) if str(node["href"]).startswith("#")})
    return anchors, links


def normalize_html_fragment(html: str) -> str:
    soup = BeautifulSoup(html, "html.parser")
    for tag in soup.find_all(True):
        if tag.has_attr("style"):
            styles = parse_style_map(str(tag["style"]))
            tag["style"] = serialize_style_map(styles)
        if tag.has_attr("class"):
            attrs = dict(tag.attrs)
            attrs["class"] = " ".join(sorted(str(value) for value in (tag.get("class") or [])))
            tag.attrs = attrs
        tag.attrs = dict(sorted(tag.attrs.items()))
    decoded = soup.decode(formatter="html").strip()
    return re.sub(r">[ \t]*[\r\n]+[ \t\r\n]*<", "><", decoded)


def parse_style_map(style: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for item in tinycss2.parse_declaration_list(style, skip_whitespace=True, skip_comments=True):
        if item.type == "declaration":
            result[item.lower_name] = normalize_css_value(tinycss2.serialize(item.value))
    return result


def normalize_css_value(value: str) -> str:
    """Normalize common Canvas-equivalent CSS serialization without hiding changes."""
    normalized = " ".join(value.casefold().split())
    normalized = re.sub(r"\s*([,:/()])\s*", r"\1", normalized)
    normalized = re.sub(
        r"(?<![\w.-])(?:0+(?:\.0+)?)(?:px|em|rem|%|pt|pc|in|cm|mm|ex|ch|vh|vw|vmin|vmax)\b",
        "0",
        normalized,
    )
    short_hex = re.fullmatch(r"#([0-9a-f])([0-9a-f])([0-9a-f])", normalized)
    if short_hex:
        normalized = "#" + "".join(character * 2 for character in short_hex.groups())
    rgb = re.fullmatch(r"rgb\((\d+),(\d+),(\d+)\)", normalized)
    if rgb and all(0 <= int(component) <= 255 for component in rgb.groups()):
        normalized = "#" + "".join(f"{int(component):02x}" for component in rgb.groups())
    return normalized


def serialize_style_map(styles: dict[str, str]) -> str:
    return "; ".join(f"{name}: {styles[name]}" for name in sorted(styles))


def check_css(  # noqa: C901 - docs/backlog.md: Sprint 17 legacy hotspot.
    css_path: Path, html: str | None = None
) -> dict[str, Any]:
    if not css_path.is_file():
        raise SystemExit(f"Canvas CSS sidecar not found: {css_path}")
    rules = tinycss2.parse_stylesheet(css_path.read_text(encoding="utf-8"), skip_whitespace=True, skip_comments=True)
    errors: list[str] = []
    warnings: list[str] = []
    plans: list[dict[str, Any]] = []
    soup = BeautifulSoup(f"<div data-danvas-root>{html or ''}</div>", "html.parser") if html is not None else None
    for rule in rules:
        if rule.type == "error":
            errors.append(f"CSS parse error: {rule.message}")
            continue
        if rule.type == "at-rule":
            errors.append(f"Unsupported at-rule: @{rule.lower_at_keyword}")
            continue
        if rule.type != "qualified-rule":
            errors.append(f"Unsupported CSS rule type: {rule.type}")
            continue
        selector = tinycss2.serialize(rule.prelude).strip()
        if not selector:
            errors.append("Empty CSS selector")
            continue
        if "::" in selector or re.search(r":(?!not\(|is\(|where\()[\w-]+", selector):
            errors.append(f"Pseudo selectors are unsupported: {selector}")
            continue
        declarations: dict[str, str] = {}
        for item in tinycss2.parse_declaration_list(rule.content, skip_whitespace=True, skip_comments=True):
            if item.type == "error":
                errors.append(f"{selector}: {item.message}")
            elif item.type != "declaration":
                errors.append(f"{selector}: unsupported CSS token {item.type}")
            else:
                value = " ".join(tinycss2.serialize(item.value).split())
                if item.lower_name.startswith("--") or item.lower_name not in SAFE_CSS_PROPERTIES:
                    errors.append(f"{selector}: unsupported property {item.lower_name}")
                elif item.important:
                    errors.append(f"{selector}: !important is unsupported")
                elif unsafe_css_value(value):
                    errors.append(f"{selector}: unsafe or external value for {item.lower_name}")
                else:
                    declarations[item.lower_name] = value
        matches: list[Tag] = []
        if soup is not None:
            try:
                matches = list(soup.select(selector))
            except Exception as exc:
                errors.append(f"Unsupported selector {selector!r}: {exc}")
                continue
            if not matches:
                warnings.append(f"Selector matched no elements: {selector}")
        plans.append({"selector": selector, "matches": len(matches), "declarations": declarations, "_nodes": matches})
    return {
        "profile": COMPATIBILITY_PROFILE,
        "css_path": str(css_path),
        "errors": errors,
        "warnings": warnings,
        "rules": [{key: value for key, value in plan.items() if key != "_nodes"} for plan in plans],
        "_plans": plans,
        "_soup": soup,
    }


def check_and_inline_css(css_path: Path, html: str) -> tuple[dict[str, Any], str]:
    report = check_css(css_path, html)
    soup = report.pop("_soup")
    plans = report.pop("_plans")
    conflicts: set[str] = set()
    for plan in plans:
        for node in plan["_nodes"]:
            styles = parse_style_map(str(node.get("style") or ""))
            for name, value in plan["declarations"].items():
                if name in styles and styles[name] != value:
                    conflicts.add(f"{plan['selector']}: {name} overrides an earlier value")
                styles[name] = value
            if styles:
                node["style"] = serialize_style_map(styles)
    report["warnings"].extend(sorted(conflicts))
    root = soup.find("div", attrs={"data-danvas-root": True})
    return report, inner_html(root)


def inner_html(node: Tag | None) -> str:
    return "" if node is None else "".join(str(child) for child in node.contents).strip()


def format_css_errors(path: Path, report: dict[str, Any]) -> str:
    return f"Canvas CSS failed profile {COMPATIBILITY_PROFILE} ({path}): " + "; ".join(report["errors"])


def page_record(page: Any) -> dict[str, Any]:
    raw = canvas_object_to_dict(page)
    def value(*names: str, default: Any = "") -> Any:
        for name in names:
            found = getattr(page, name, None)
            if found is None:
                found = raw.get(name)
            if found is not None:
                return found
        return default
    return {
        "page_id": value("page_id", "id"),
        "url": value("url"),
        "html_url": value("html_url"),
        "title": value("title"),
        "published": bool(value("published", default=False)),
        "front_page": bool(value("front_page", default=False)),
        "editing_roles": value("editing_roles"),
        "publish_at": value("publish_at"),
        "updated_at": value("updated_at"),
        "body": str(value("body")),
    }
